#!/bin/sh
# This script creates or updates the regions Java file with a query to Wikidata

request_url='https://query.wikidata.org/sparql?query=SELECT%20%3FregionCode%20%3Fcoordinates%0AWHERE%20%7B%0A%20%20%7B%0A%20%20%20%20%3Fitem%20wdt%3AP297%20%3FregionCode%20%3B%20%23%20ISO%203166-1%20alpha-2%20code%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP625%20%3Fcoordinates%20.%0A%20%20%7D%0A%20%20UNION%20%7B%0A%20%20%20%20%3Fitem%20wdt%3AP2082%20%3FregionCode%20%3B%20%23%20M.49%20code%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP625%20%3Fcoordinates%20.%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0AORDER%20BY%20%3FregionCode'
temp_file="temp.regions.csv"
java_file="src/main/java/com/github/nikalon/sunsync/Regions.java"

curl  ${request_url} -H 'Accept: text/csv' | tail +2 > ${temp_file}
region_count=`wc -l ${temp_file} | awk '{print $1}'`

# Create/Overwrite Java file
echo '// This file was auto-generated by "regions.sh" script. DO NOT CHANGE MANUALLY.

package com.github.nikalon.sunsync;

import java.util.Hashtable;
import java.util.Map;

import com.github.nikalon.sunsync.Sun.GeographicCoordinate;

public class Regions {' > ${java_file}
#echo '    private static final int REGION_COUNT = 10;' > ${java_file}
wc -l ${temp_file} | awk '{printf("    private static final int REGION_COUNT = %s;\n", $1)}' >> ${java_file}
echo '    public static final Map<String, GeographicCoordinate> REGIONS = new Hashtable<String, GeographicCoordinate>(REGION_COUNT){{' >> ${java_file}
cat ${temp_file} | awk -F "[,( )]" '{printf("        put(\"%s\", GeographicCoordinate.fromDecimalDegrees(%s, %s));\n", $1, $4, $3)}' >> ${java_file}
echo -n '    }};
}' >> ${java_file}

# Clean up
rm ${temp_file}