name: SunSync
version: 0.1-SNAPSHOT
main: com.github.nikalon.sunsync.SunSync
api-version: 1.18
commands:
  timesync:
    description: Query or change SunSync options
    usage: "Usage: /<command> [location|syncIntervalSec|clock|debugMode|continue|pause] <value>"